### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by codetestmg** [madmatt/id3global-service#16]
could you please provide sample data for pilot env to test pass results?

Thanks

**Comment by madmatt** [comment]
Hi @codetestmg, sorry for the delay, unfortunately, I no longer have access to the environment I was doing my testing in so can't help with that.

ID3Global have an authenticated service that you can login to - from there as I recall they have documentation that lists valid information for different countries in an Excel document from memory. IIRC it's not https://pilot.id3global.com/ but another similar URL. Sorry I can't be more helpful!
