### ISSUE TITLE
Previous Addresses

### ISSUE THREAD

**Issue by mic2100** [madmatt/id3global-service#7]
Hi,

This is more an a query than an issue.

I'm looking at using this on a project I'm currently working. I can see that the `AddressContainer` has code for the current address. How do you put in previous addresses 1-3? or has that code not been written yet?

Many Thanks Mike

**Comment by madmatt** [comment]
Hi @mic2100,

This hasn't been written yet, but should be fairly easy to drop in (a matter of adding more methods to the `AddressContainer`, and then adding them to the XML request made to ID3. If you're needing to do this, please feel free to submit a pull request with the changed code and we can incorporate it into the module.

Cheers,
Matt.

**Comment by madmatt** [comment]
Closing this issue (4 years later :D) as the original query is answered.
